### ISSUE TITLE
can i know how to convert boolean

### ISSUE THREAD

**Issue by SungJJinKang** [Benzino/ExcelToJsonConverter#1]
i type 'true' "true" true ...... to value, but i cant get boolean value

**Comment by Benzino** [comment]
Booleans should work. Are you getting an error? If so can you send it on to me please. If I recall correctly, caps are important. So try True or TRUE. It's being a while since I worked on this project, but if the above does not work let me know and I can look into it more.

**Comment by SungJJinKang** [comment]
yeah i tried True , TRUE   .
but converter convert this as string......
i got no error

**Comment by Benzino** [comment]
That is the correct behaviour, to save it as a string. You can then convert it to a boolean when parsing.

In C#:
`bool foo = bool.parse("true");`

It should also work if you use the [JsonProperty] for a bool property if you are deserialize the json to an object.

**Comment by SungJJinKang** [comment]
ah thank you i solve this problem thanks to you
