### ISSUE TITLE
i can't get array values

### ISSUE THREAD

**Issue by SungJJinKang** [Benzino/ExcelToJsonConverter#2]
i writed {1,5} in excel
and convert this to json
and then i cant know how to set this to array

**Comment by Benzino** [comment]
Hey, so this extension is just for converting excel to json, parsing that json really has nothing to do with this project. I'd suggest you research more on that topic to help you understand it more, and also json data as well ({1,5} is not the correct format for an array).

Some results on google that may help you:
[Json Arrays](https://www.w3schools.com/js/js_json_arrays.asp)
[Parsing Json Array in c#](https://stackoverflow.com/questions/15726197/parsing-a-json-array-using-json-net)
